import { useState } from "react";
import { env } from "../env";
import { sendChatQuestion } from "../api/chatApi";
import type { ChatMessage } from "../types/chat";
import type { DashboardContext } from "../types/tableau";
import DashboardContextPanel from "./DashboardContextPanel";
import MessageInput from "./MessageInput";
import MessageList from "./MessageList";

type Props = {
  dashboardContext: DashboardContext;
  authToken?: string;
  userEmail?: string;
};

export default function ChatPanel({ dashboardContext, authToken, userEmail }: Props) {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: "welcome",
      role: "assistant",
      content: "Ask me what this Tableau dashboard is showing. For this PoC, answers are generated by a mock provider.",
      createdAt: new Date().toISOString(),
    },
  ]);
  const [sessionId, setSessionId] = useState<string | undefined>();
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleSend(question: string) {
    const trimmedQuestion = question.trim();
    if (!trimmedQuestion || isLoading) {
      return;
    }

    const userMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: "user",
      content: trimmedQuestion,
      createdAt: new Date().toISOString(),
    };

    setMessages((current) => [...current, userMessage]);
    setIsLoading(true);
    setError(null);

    try {
      const response = await sendChatQuestion({
        question: trimmedQuestion,
        dashboardContext,
        clientContext: {
          source: "tableau-extension",
          appVersion: env.appVersion,
        },
        sessionId,
      }, authToken);

      setSessionId(response.sessionId);
      setMessages((current) => [
        ...current,
        {
          id: response.messageId,
          role: "assistant",
          content: response.answer,
          createdAt: new Date().toISOString(),
        },
      ]);
    } catch (unknownError) {
      setError(unknownError instanceof Error ? unknownError.message : "Failed to send the question.");
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <section className="chat-panel" aria-label="Tableau Assistant chat panel">
      <header className="chat-header">
        <div>
          <h1>Tableau Assistant</h1>
          <p>Ask questions about this dashboard</p>
        </div>
        <span className="status-pill">PoC</span>
      </header>
      {userEmail ? <div className="user-strip">Signed in as {userEmail}</div> : null}

      <DashboardContextPanel dashboardContext={dashboardContext} />
      <MessageList messages={messages} isLoading={isLoading} />

      {error ? <div className="error-banner">{error}</div> : null}

      <MessageInput disabled={isLoading} onSend={handleSend} />
    </section>
  );
}
